version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]   # Only needed if you're using GPU
    volumes:
      - ollama_data:/root/.ollama  # Persist models across restarts
    restart: unless-stopped

volumes:
  ollama_data:
